### ISSUE TITLE
add ability

### ISSUE THREAD

**Issue by CalamityZeroRP** [CalamityZeroRP/FiveM#47]
for ems, pd, and mechanics to clock in and out in game as available

**Comment by Ahwicks** [comment]
Are you looking for an "On Duty" Script or a time management script which displays how long an First Responder/Mechanic has worked in X amount of days / in the past week? 

A good option is [Badger](https://docs.badger.store/fivem-discord-scripts/policeemsactivity) You can set it for PD/EMS and such. It has integrations with Discord as well.
